### ISSUE TITLE
Home Link 404 Error

### ISSUE THREAD

**Issue by Jeetu95** [antew7/number-system#6]
Clicking on the Home Link on the webpage is giving a 404 error. It is redirecting to "front.html" page instead of "index.html" page

**Comment by Jeetu95** [comment]
Hello, @antew7 I found that your website is showing error 404 for clicking on "Home" link. So I went ahead and fixed the issue.
#8 Here is the Pull Request. Please check it and merge it to resolve the issue. If done then please close this issue.

Thank you

**Comment by antew7** [comment]
I merged your PR. Thanks :)
